### ISSUE TITLE
I can‘t run the demo

### ISSUE THREAD

**Issue by llllljw** [DuncanZauss/Keypoint_Communities#16]
Hey, why I run python3 -m openpifpaf.predict docs/11790.jpg --checkpoint=shufflenetv2k30-wholebody --line-width=2 --show, it shows：
Traceback (most recent call last):
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jiawen/anaconda3/envs/KPTCOM/lib/python3.9/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
Could u pls help me

**Comment by llllljw** [comment]
maybe i didn‘t install torch, I install openpifpaf again, and the error seems disappear

**Comment by DuncanZauss** [comment]
Great that you resolved the issue!
