### ISSUE TITLE
Problems during operation

### ISSUE THREAD

**Issue by hechengbo-H** [DuncanZauss/Keypoint_Communities#8]
Hello author, I'm trying to re-implement your code, but in the process, I'm encountering problems.
First I need to state that I successfully installed the environment and ran the steps: python Compute_edge_weights.py
Secondly， After running this command (python Compute_training_weights.py) the following error is reported：

Traceback (most recent call last):
  File "/home/hcb/Keypoint_Communities/src/Compute_training_weights.py", line 314, in <module>
    create_weights_wholebody()
  File "/home/hcb/Keypoint_Communities/src/Compute_training_weights.py", line 192, in create_weights_wholebody
    draw_skeletons_wb(WHOLEBODY_STANDING_POSE, inverse_normalize(w_harm_cl_euclid, kps=kps),
  File "/home/hcb/Keypoint_Communities/src/Compute_training_weights.py", line 60, in draw_skeletons_wb
    from openpifpaf.annotation import Annotation  # pylint: disable=import-outside-toplevel
  File "/home/hcb/anaconda3/envs/keypoint/lib/python3.8/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/home/hcb/anaconda3/envs/keypoint/lib/python3.8/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/home/hcb/anaconda3/envs/keypoint/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/hcb/anaconda3/envs/keypoint/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/hcb/anaconda3/envs/keypoint/lib/python3.8/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
![directory](https://user-images.githubusercontent.com/70620882/140066943-4405ec2c-22ea-4260-b751-2e35f91654b7.png)

（I only changed the path, no other code was touched. The code can generate a folder named docs_wb, but it is empty.My directory is shown in the figure）
   

cheers

**Comment by DuncanZauss** [comment]
Hello @hechengbo-H,
Thank you for the interest in our work!
Which OS and pytorch version are you using?

**Comment by shashankvasisht** [comment]
Hi I'm facing the exact same issue. i am on a Linux machine (Ubuntu) with the torch version as mentioned in your requirements.txt. Also the python version is 3.9

**Comment by nish-sv** [comment]
Hello @DuncanZauss , I am also facing the same issue while trying to run the command.
